<?php

namespace Lle\PdfReportBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Lle\PdfReportBundle\Lib\PdfReport;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * ModeleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeleRepository extends EntityRepository
{
    public function generatePdf($code, $obj, $iterable, $webpath) {

        $modele = $this->findOneByCode($code);
        $pdf = new PdfReport(file_get_contents($webpath.'/'.$modele->getFilepath()));
        $pdf->generate($obj, $iterable);
        $tmp_file = tempnam( $webpath."/pdfs/" , "pdf_".$code."_" );
        $pdf->output($tmp_file, 'F');
        return $tmp_file;
    }
 
}
